# Generated by Django 4.2.23 on 2025-09-22 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=1)),
                ('semester', models.IntegerField(default=1)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('MID', 'Mid Semester'), ('END', 'End Semester'), ('SPL', 'Special Exam')], default='END', max_length=3)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20, unique=True)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.IntegerField(default=0)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('has_power_backup', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair accessible')),
                ('ac_available', models.BooleanField(default=False)),
                ('projector_available', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['block', 'room_id'],
            },
        ),
        migrations.CreateModel(
            name='ExamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('send_to_students', models.BooleanField(default=True)),
                ('send_to_faculty', models.BooleanField(default=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=10)),
                ('recipients_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.exam')),
            ],
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('special_arrangement', models.BooleanField(default=False)),
                ('arrangement_notes', models.TextField(blank=True, help_text='Any special seating requirements')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='seat_qrcodes/')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seat_allocations', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.exam')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'ordering': ['exam', 'room', 'row', 'column'],
                'unique_together': {('exam', 'room', 'row', 'column'), ('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_allocated', models.IntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reporting_time', models.TimeField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_room_allocations', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.exam')),
                ('invigilator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.faculty')),
                ('relief_invigilator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_duties', to='accounts.faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.room')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_room_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exam', 'room'],
                'unique_together': {('exam', 'room')},
            },
        ),
        migrations.CreateModel(
            name='ExamCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('pass_marks', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('duration_mins', models.IntegerField(default=180)),
                ('instructions', models.TextField(blank=True)),
                ('question_paper_code', models.CharField(blank=True, max_length=20)),
                ('has_practical', models.BooleanField(default=False)),
                ('practical_date', models.DateField(blank=True, null=True)),
                ('practical_duration_mins', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_courses', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluator_courses', to='accounts.faculty')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='admin_portal.exam')),
                ('examiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_courses', to='accounts.faculty')),
            ],
            options={
                'ordering': ['exam', 'course'],
                'unique_together': {('exam', 'course')},
            },
        ),
    ]
