# Generated by Django 4.2.23 on 2025-09-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_portal', '0002_examnotification'),
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examnotification',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Admin Exam Notification', 'verbose_name_plural': 'Admin Exam Notifications'},
        ),
        migrations.AlterField(
            model_name='examnotification',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='faculty_portal.exam'),
        ),
    ]
