# Generated by Django 4.2.23 on 2025-09-22 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalpracticeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='malpractice_evidence/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WitnessStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_remarks', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_statements', to=settings.AUTH_USER_MODEL)),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witness_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MalpracticeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('SEVERE', 'Severe')], default='LOW', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('INVESTIGATING', 'Under Investigation'), ('ACTION_PENDING', 'Action Pending'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='REPORTED', max_length=15)),
                ('primary_evidence', models.FileField(blank=True, help_text='Main evidence file', null=True, upload_to='malpractice_evidence/')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('investigation_started_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True)),
                ('penalty_imposed', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('committee_remarks', models.TextField(blank=True)),
                ('appeal_filed', models.BooleanField(default=False)),
                ('appeal_status', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_evidence', models.ManyToManyField(blank=True, to='faculty_portal.malpracticeevidence')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_portal.exam')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to='accounts.faculty')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to='accounts.faculty')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_portal.room')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reports', to=settings.AUTH_USER_MODEL)),
                ('witness_statements', models.ManyToManyField(blank=True, to='faculty_portal.witnessstatement')),
            ],
            options={
                'verbose_name': 'Malpractice Report',
                'verbose_name_plural': 'Malpractice Reports',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('START', 'Started'), ('PAUSE', 'Paused'), ('RESUME', 'Resumed'), ('END', 'Ended'), ('INCIDENT', 'Incident'), ('OTHER', 'Other')], max_length=10)),
                ('description', models.TextField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('affected_students', models.ManyToManyField(blank=True, to='accounts.student')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.exam')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.faculty')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_portal.room')),
            ],
            options={
                'verbose_name': 'Exam Log',
                'verbose_name_plural': 'Exam Logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='ABSENT', max_length=10)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.exam')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-marked_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
