# Generated by Django 4.2.23 on 2025-09-17 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical')], default='THEORY', max_length=10)),
                ('year', models.IntegerField(default=1)),
                ('semester', models.IntegerField(default=1)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('rows_count', models.IntegerField()),
                ('columns_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MalpracticeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('proof_url', models.URLField(blank=True, max_length=255)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.exam')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.faculty')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_portal.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='ABSENT', max_length=10)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.exam')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.faculty')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_portal.student')),
            ],
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('column_number', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.exam')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_portal.student')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='FacultyExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.exam')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.room')),
            ],
            options={
                'unique_together': {('exam', 'faculty', 'room')},
            },
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_capacity', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.exam')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.room')),
            ],
            options={
                'unique_together': {('exam', 'room')},
            },
        ),
        migrations.CreateModel(
            name='ExamCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_portal.course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_portal.exam')),
            ],
            options={
                'unique_together': {('exam', 'course')},
            },
        ),
    ]
