# Generated by Django 4.2.23 on 2025-09-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_notifications', to='faculty_portal.exam')),
            ],
            options={
                'verbose_name': 'Faculty Exam Notification',
                'verbose_name_plural': 'Faculty Exam Notifications',
            },
        ),
    ]
